import type {
  ArchiveEntry,
  ImportBatch,
  Recording,
  ReleaseRecord,
  Site,
  Snapshot,
  StudyState,
} from "../domain/models";

const stamp = "2026-09-08T09:00:00.000Z";
const summerBatch: ImportBatch = {
  id: "batch-summer-2026",
  label: "Summer 2026 field import",
  status: "completed",
  createdAt: "2026-06-10T08:00:00.000Z",
  updatedAt: "2026-07-10T16:30:00.000Z",
  completedAt: "2026-07-10T16:30:00.000Z",
};
// Last touched in May and never completed: past the 90 day unfinished-import window.
const staleBatch: ImportBatch = {
  id: "batch-spring-leftovers",
  label: "Spring lecture leftovers",
  status: "open",
  createdAt: "2026-04-18T10:00:00.000Z",
  updatedAt: "2026-05-02T11:15:00.000Z",
};
const liveIntakeBatch: ImportBatch = {
  id: "batch-live-intake",
  label: "Current intake",
  status: "open",
  createdAt: "2026-09-01T08:00:00.000Z",
  updatedAt: stamp,
};
const recordings: Recording[] = [
  {
    id: "rec-underpass",
    catalogId: "SC-26-001",
    title: "Underpass reverb at dawn",
    source: "Lin Qiao",
    recordedOn: "2026-06-14",
    format: "WAV",
    location: "Mason Street underpass",
    summary:
      "Footsteps, bicycle tires, and the first bus fold into a long concrete echo.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 154,
    },
    signalRole: "arrival",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["mobility", "morning", "echo"],
    color: "#d7654e",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-market",
    catalogId: "SC-26-002",
    title: "Market bell sequence",
    source: "Amina Patel",
    recordedOn: "2026-06-18",
    format: "WAV",
    location: "Riverside produce market",
    summary:
      "Vendor bells, crate wheels, and short greetings form a changing lunchtime pulse.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 218,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["market", "voices", "work"],
    color: "#7c6aa6",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-tram",
    catalogId: "SC-26-003",
    title: "Tram brake chorus",
    source: "Rosa Mendes",
    recordedOn: "2026-06-20",
    format: "FLAC",
    location: "East Loop platform",
    summary:
      "A layered study of arriving trams, platform announcements, and departing doors.",
    audioSpec: {
      sampleRate: 96000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 187,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "metal", "rhythm"],
    color: "#2f7c75",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-courtyard",
    catalogId: "SC-26-004",
    title: "Courtyard conversation",
    source: "North Block listening circle",
    recordedOn: "2026-06-23",
    format: "WAV",
    location: "North Block courtyard",
    summary:
      "Neighbors discuss the shade trees while children play beyond the microphone.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 241,
    },
    signalRole: "voice",
    sensitivity: "restricted",
    transcriptStatus: "draft",
    consentStatus: "pending",
    isFeatured: true,
    tags: ["oral history", "neighborhood", "care"],
    color: "#c7903d",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-drain",
    catalogId: "SC-26-005",
    title: "Storm drain resonance",
    source: "Riverside youth lab",
    recordedOn: "2026-06-26",
    format: "WAV",
    location: "Canal walk",
    summary:
      "Rainwater and passing trains turn the storm drain into a low, shifting instrument.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 201,
    },
    signalRole: "voice",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["water", "weather", "youth"],
    color: "#3f6fa8",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-workshop",
    catalogId: "SC-26-006",
    title: "Ceramic workshop pulse",
    source: "Jae Min",
    recordedOn: "2026-07-01",
    format: "FLAC",
    location: "Clay Lane studios",
    summary:
      "Throwing wheels, trimming tools, and a quiet count-in before firing.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 166,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["craft", "hands", "rhythm"],
    color: "#8c9474",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-bus",
    catalogId: "SC-26-007",
    title: "Evening bus loop",
    source: "Milo Chen",
    recordedOn: "2026-07-04",
    format: "WAV",
    location: "Route 11 terminus",
    summary:
      "The last loop of the evening: ticket beeps, a driver’s goodbye, and an emptying carriage.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 193,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "evening", "routine"],
    color: "#a55f72",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-park",
    catalogId: "SC-26-008",
    title: "Park fence harmonics",
    source: "Elena Matic",
    recordedOn: "2026-07-08",
    format: "WAV",
    location: "Juniper Park",
    summary:
      "Wind and a loose fence panel make a soft tonal figure beside an afternoon game.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 128,
    },
    signalRole: "departure",
    sensitivity: "sensitive",
    transcriptStatus: "missing",
    consentStatus: "restricted",
    isFeatured: false,
    tags: ["park", "wind", "play"],
    color: "#597b8e",
    importBatchId: summerBatch.id,
    createdAt: stamp,
    updatedAt: stamp,
  },
  // Clip stuck in the unfinished, long-stale import batch.
  {
    id: "rec-lecture",
    catalogId: "SC-26-104",
    title: "Lecture hall room tone",
    source: "Civic archive pilot",
    recordedOn: "2026-04-25",
    format: "WAV",
    location: "Old lecture hall",
    summary:
      "Long empty-room tone captured during an abandoned indoor listening pilot.",
    audioSpec: {
      sampleRate: 48000,
      channels: 1,
      bitDepth: 24,
      durationSeconds: 96,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "pending",
    isFeatured: false,
    tags: ["indoor", "room-tone"],
    color: "#8a8f98",
    importBatchId: staleBatch.id,
    createdAt: "2026-04-25T09:20:00.000Z",
    updatedAt: "2026-05-02T11:15:00.000Z",
  },
];
const sites: Site[] = [
  {
    id: "site-threshold",
    name: "Threshold listening",
    shortLabel: "Threshold",
    prompt:
      "What changes when you stop and listen before crossing into the neighborhood?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#d7654e",
    sequence: 0,
    recordingIds: ["rec-underpass"],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "site-rhythm",
    name: "Daily rhythms",
    shortLabel: "Rhythms",
    prompt:
      "Which repeated sounds tell us how work, transit, and care share a day?",
    maxDurationSeconds: 540,
    maxClips: 3,
    quietSpace: false,
    hasSeating: true,
    color: "#7c6aa6",
    sequence: 1,
    recordingIds: ["rec-market", "rec-tram"],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "site-voices",
    name: "Shared voices",
    shortLabel: "Voices",
    prompt:
      "Whose voices need context, consent, or a slower place to be heard?",
    maxDurationSeconds: 480,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#2f7c75",
    sequence: 2,
    recordingIds: ["rec-courtyard"],
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "site-return",
    name: "Return and release",
    shortLabel: "Return",
    prompt: "What should remain audible after the route ends?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#597b8e",
    sequence: 3,
    // rec-rooftop was archived with its import batch; the route reference is
    // intentionally retained and still resolves to the archived clip.
    recordingIds: ["rec-bus", "rec-rooftop"],
    createdAt: stamp,
    updatedAt: "2026-08-12T14:00:00.000Z",
  },
  // Empty site last touched before the 120 day disused-site window.
  {
    id: "site-civic-hall",
    name: "Civic hall foyer",
    shortLabel: "Civic hall",
    prompt: "How does an official waiting room change the pace of listening?",
    maxDurationSeconds: 360,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#9b8ec4",
    sequence: 4,
    recordingIds: [],
    createdAt: "2026-02-14T09:00:00.000Z",
    updatedAt: "2026-03-01T09:00:00.000Z",
  },
];

// Archived winter import: cleaned up already, but one of its clips is still
// referenced by the route and a finding, so the archive keeps it resolvable.
const archivedRooftop: Recording = {
  id: "rec-rooftop",
  catalogId: "SC-25-091",
  title: "Rooftop snowfall hush",
  source: "Winter pilot team",
  recordedOn: "2025-12-30",
  format: "WAV",
  location: "Harbor rooftop",
  summary:
    "Distant harbor work and muffled snowfall from a since-archived winter pilot.",
  audioSpec: {
    sampleRate: 48000,
    channels: 2,
    bitDepth: 24,
    durationSeconds: 142,
  },
  signalRole: "departure",
  sensitivity: "public",
  transcriptStatus: "verified",
  consentStatus: "confirmed",
  isFeatured: false,
  tags: ["winter", "harbor"],
  color: "#7a93b5",
  importBatchId: "batch-winter-pilot",
  createdAt: "2026-01-04T10:00:00.000Z",
  updatedAt: "2026-02-20T10:00:00.000Z",
};
const winterArchive: ArchiveEntry = {
  id: "archive-winter-pilot",
  kind: "import",
  archivedAt: "2026-08-28T08:00:00.000Z",
  reason: "Completed import passed its 180 day window",
  retentionLabel: "Completed import",
  importBatch: {
    id: "batch-winter-pilot",
    label: "Winter pilot import",
    status: "completed",
    createdAt: "2026-01-04T10:00:00.000Z",
    updatedAt: "2026-02-20T10:00:00.000Z",
    completedAt: "2026-02-20T10:00:00.000Z",
  },
  recordings: [archivedRooftop],
};

function expiredPublication(): {
  release: ReleaseRecord;
  snapshot: Snapshot;
} {
  const generatedAt = "2025-08-15T12:00:00.000Z";
  const byId = new Map(recordings.map((recording) => [recording.id, recording]));
  const snapshot: Snapshot = {
    schemaVersion: 2,
    generatedAt,
    releaseId: "release-2025-summer",
    releaseSequence: 1,
    revision: 42,
    fingerprint: "sc-r1-legacy2025",
    project: {
      id: "signal-commons-2025",
      title: "Signal Commons: Harbor Winter Notes",
      fieldArea: "Harbor district",
      listeningQuestion: "What stays audible in the quiet season?",
      publicationDate: "2025-09-01",
      stage: "ready",
      lastReadinessCheck: generatedAt,
    },
    preferences: { pace: "steady", accessPriority: 60, listenerCount: 5 },
    summary: {
      recordingCount: recordings.length,
      siteCount: 4,
      routeSeconds: 740,
      readinessScore: 100,
    },
    sites: sites
      .filter((site) => site.id !== "site-civic-hall")
      .map((site) => ({
        ...site,
        recordingIds: site.recordingIds.filter((id) => id !== "rec-rooftop"),
        recordings: site.recordingIds
          .filter((id) => id !== "rec-rooftop")
          .map((id) => byId.get(id))
          .filter((recording): recording is Recording => Boolean(recording)),
      })),
    unresolvedIssues: [],
  };
  const release: ReleaseRecord = {
    id: "release-2025-summer",
    sequence: 1,
    createdAt: generatedAt,
    status: "ready",
    revision: 42,
    fingerprint: snapshot.fingerprint,
    readiness: {
      ready: true,
      score: 100,
      blockers: [],
      cautions: [],
      checkedAt: generatedAt,
    },
    snapshot,
  };
  return { release, snapshot };
}

export function createSeedStudy(): StudyState {
  const { release: historicalRelease } = expiredPublication();
  return structuredClone({
    version: 3,
    revision: 0,
    updatedAt: stamp,
    project: {
      id: "signal-commons-2026",
      title: "Signal Commons: Listening Across the City",
      fieldArea: "Riverside neighborhoods",
      listeningQuestion:
        "How do everyday crossings, work, and care sound when residents lead the record?",
      publicationDate: "2026-10-02",
      stage: "review",
    },
    recordings,
    importBatches: [summerBatch, staleBatch, liveIntakeBatch],
    sites,
    issues: [
      {
        id: "issue-consent",
        title: "Confirm courtyard release scope",
        description:
          "The listening circle needs to confirm whether the full conversation can be included in the public route.",
        severity: "critical",
        status: "open",
        recordingId: "rec-courtyard",
        siteId: "site-voices",
        owner: "Amina Patel",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "issue-transcript",
        title: "Add transcript for storm drain clip",
        description:
          "Prepare a concise transcript and sound description before the youth lab clip is released.",
        severity: "warning",
        status: "in-progress",
        recordingId: "rec-drain",
        owner: "Lin Qiao",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        // Link still resolves even though the clip's import was archived.
        id: "issue-rooftop-note",
        title: "Note rooftop ending reuse",
        description:
          "Decide whether the archived winter pilot ending should be restored for this route.",
        severity: "note",
        status: "open",
        recordingId: "rec-rooftop",
        owner: "Milo Chen",
        createdAt: "2026-08-30T09:00:00.000Z",
        updatedAt: "2026-08-30T09:00:00.000Z",
      },
    ],
    preferences: { pace: "steady", accessPriority: 70, listenerCount: 6 },
    auditLog: [],
    release: null,
    releaseHistory: [historicalRelease],
    archive: [winterArchive],
  });
}
