import type {
  ImportBatch,
  Recording,
  Site,
  StudyState,
} from "../domain/models";
import { DEFAULT_RETENTION_POLICY, emptyTombstones } from "../domain/retention";

const stamp = "2026-09-08T09:00:00.000Z";
const recordings: Recording[] = [
  {
    id: "rec-underpass",
    catalogId: "SC-26-001",
    title: "Underpass reverb at dawn",
    source: "Lin Qiao",
    recordedOn: "2026-06-14",
    format: "WAV",
    location: "Mason Street underpass",
    summary:
      "Footsteps, bicycle tires, and the first bus fold into a long concrete echo.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 154,
    },
    signalRole: "arrival",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["mobility", "morning", "echo"],
    color: "#d7654e",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-market",
    catalogId: "SC-26-002",
    title: "Market bell sequence",
    source: "Amina Patel",
    recordedOn: "2026-06-18",
    format: "WAV",
    location: "Riverside produce market",
    summary:
      "Vendor bells, crate wheels, and short greetings form a changing lunchtime pulse.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 218,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "draft",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["market", "voices", "work"],
    color: "#7c6aa6",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-tram",
    catalogId: "SC-26-003",
    title: "Tram brake chorus",
    source: "Rosa Mendes",
    recordedOn: "2026-06-20",
    format: "FLAC",
    location: "East Loop platform",
    summary:
      "A layered study of arriving trams, platform announcements, and departing doors.",
    audioSpec: {
      sampleRate: 96000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 187,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "metal", "rhythm"],
    color: "#2f7c75",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-courtyard",
    catalogId: "SC-26-004",
    title: "Courtyard conversation",
    source: "North Block listening circle",
    recordedOn: "2026-06-23",
    format: "WAV",
    location: "North Block courtyard",
    summary:
      "Neighbors discuss the shade trees while children play beyond the microphone.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 241,
    },
    signalRole: "voice",
    sensitivity: "restricted",
    transcriptStatus: "draft",
    consentStatus: "pending",
    isFeatured: true,
    tags: ["oral history", "neighborhood", "care"],
    color: "#c7903d",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-drain",
    catalogId: "SC-26-005",
    title: "Storm drain resonance",
    source: "Riverside youth lab",
    recordedOn: "2026-06-26",
    format: "WAV",
    location: "Canal walk",
    summary:
      "Rainwater and passing trains turn the storm drain into a low, shifting instrument.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 201,
    },
    signalRole: "voice",
    sensitivity: "public",
    transcriptStatus: "missing",
    consentStatus: "confirmed",
    isFeatured: true,
    tags: ["water", "weather", "youth"],
    color: "#3f6fa8",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-workshop",
    catalogId: "SC-26-006",
    title: "Ceramic workshop pulse",
    source: "Jae Min",
    recordedOn: "2026-07-01",
    format: "FLAC",
    location: "Clay Lane studios",
    summary:
      "Throwing wheels, trimming tools, and a quiet count-in before firing.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 166,
    },
    signalRole: "texture",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["craft", "hands", "rhythm"],
    color: "#8c9474",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-bus",
    catalogId: "SC-26-007",
    title: "Evening bus loop",
    source: "Milo Chen",
    recordedOn: "2026-07-04",
    format: "WAV",
    location: "Route 11 terminus",
    summary:
      "The last loop of the evening: ticket beeps, a driver’s goodbye, and an emptying carriage.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 193,
    },
    signalRole: "departure",
    sensitivity: "public",
    transcriptStatus: "verified",
    consentStatus: "confirmed",
    isFeatured: false,
    tags: ["transit", "evening", "routine"],
    color: "#a55f72",
    createdAt: stamp,
    updatedAt: stamp,
  },
  {
    id: "rec-park",
    catalogId: "SC-26-008",
    title: "Park fence harmonics",
    source: "Elena Matic",
    recordedOn: "2026-07-08",
    format: "WAV",
    location: "Juniper Park",
    summary:
      "Wind and a loose fence panel make a soft tonal figure beside an afternoon game.",
    audioSpec: {
      sampleRate: 48000,
      channels: 2,
      bitDepth: 24,
      durationSeconds: 128,
    },
    signalRole: "departure",
    sensitivity: "sensitive",
    transcriptStatus: "missing",
    consentStatus: "restricted",
    isFeatured: false,
    tags: ["park", "wind", "play"],
    color: "#597b8e",
    importBatchId: "batch-workshop",
    createdAt: stamp,
    updatedAt: stamp,
  },
];

const EARLY_IMPORT_IDS = [
  "rec-underpass",
  "rec-market",
  "rec-tram",
  "rec-courtyard",
  "rec-drain",
];
recordings.forEach((recording) => {
  if (!recording.importBatchId) {
    recording.importBatchId = EARLY_IMPORT_IDS.includes(recording.id)
      ? "batch-summer"
      : "batch-workshop";
  }
});

const importBatches: ImportBatch[] = [
  {
    id: "batch-summer",
    label: "Summer listening intake",
    source: "Field recorder archive",
    note: "June neighbourhood sweep imported before catalog review.",
    status: "completed",
    recordingIds: EARLY_IMPORT_IDS,
    createdAt: stamp,
    completedAt: stamp,
  },
  {
    id: "batch-workshop",
    label: "July supplement",
    source: "Contributor shared drives",
    note: "Late clips awaiting transcript and consent confirmation.",
    status: "open",
    recordingIds: ["rec-workshop", "rec-bus", "rec-park"],
    createdAt: stamp,
  },
];
const sites: Site[] = [
  {
    id: "site-threshold",
    name: "Threshold listening",
    shortLabel: "Threshold",
    prompt:
      "What changes when you stop and listen before crossing into the neighborhood?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#d7654e",
    sequence: 0,
    recordingIds: ["rec-underpass"],
    updatedAt: stamp,
  },
  {
    id: "site-rhythm",
    name: "Daily rhythms",
    shortLabel: "Rhythms",
    prompt:
      "Which repeated sounds tell us how work, transit, and care share a day?",
    maxDurationSeconds: 540,
    maxClips: 3,
    quietSpace: false,
    hasSeating: true,
    color: "#7c6aa6",
    sequence: 1,
    recordingIds: ["rec-market", "rec-tram"],
    updatedAt: stamp,
  },
  {
    id: "site-voices",
    name: "Shared voices",
    shortLabel: "Voices",
    prompt:
      "Whose voices need context, consent, or a slower place to be heard?",
    maxDurationSeconds: 480,
    maxClips: 2,
    quietSpace: true,
    hasSeating: true,
    color: "#2f7c75",
    sequence: 2,
    recordingIds: ["rec-courtyard"],
    updatedAt: stamp,
  },
  {
    id: "site-return",
    name: "Return and release",
    shortLabel: "Return",
    prompt: "What should remain audible after the route ends?",
    maxDurationSeconds: 420,
    maxClips: 3,
    quietSpace: false,
    hasSeating: false,
    color: "#597b8e",
    sequence: 3,
    recordingIds: ["rec-bus"],
    updatedAt: stamp,
  },
];
export function createSeedStudy(): StudyState {
  return structuredClone({
    version: 3,
    revision: 0,
    updatedAt: stamp,
    project: {
      id: "signal-commons-2026",
      title: "Signal Commons: Listening Across the City",
      fieldArea: "Riverside neighborhoods",
      listeningQuestion:
        "How do everyday crossings, work, and care sound when residents lead the record?",
      publicationDate: "2026-10-02",
      stage: "review",
    },
    recordings,
    sites,
    issues: [
      {
        id: "issue-consent",
        title: "Confirm courtyard release scope",
        description:
          "The listening circle needs to confirm whether the full conversation can be included in the public route.",
        severity: "critical",
        status: "open",
        recordingId: "rec-courtyard",
        siteId: "site-voices",
        owner: "Amina Patel",
        createdAt: stamp,
        updatedAt: stamp,
      },
      {
        id: "issue-transcript",
        title: "Add transcript for storm drain clip",
        description:
          "Prepare a concise transcript and sound description before the youth lab clip is released.",
        severity: "warning",
        status: "in-progress",
        recordingId: "rec-drain",
        owner: "Lin Qiao",
        createdAt: stamp,
        updatedAt: stamp,
      },
    ],
    importBatches,
    retentionPolicies: DEFAULT_RETENTION_POLICY,
    retentionIndex: {},
    tombstoneIndex: emptyTombstones(),
    releaseLineage: [],
    preferences: { pace: "steady", accessPriority: 70, listenerCount: 6 },
    auditLog: [],
    release: null,
  });
}
